### PR TITLE
DBZ-3668 Add test case for CloudEventsConverter

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-3668

This PR relies on the core repository PR https://github.com/debezium/debezium/pull/2497 to be merged.

### CODE REVIEW

**Review by keweishang — APPROVED** [review]

**Comment by Naros** [comment]
Hi @keweishang, per Gunnar's request on the main PR, I've extended this PR to also include a service-loader contract so that the connectors all can provide their implementations without needing to adjust behavior in core going forward as new connectors are added to Debezium.

**Review by keweishang — APPROVED** [review]
👍

**Review by gunnarmorling — APPROVED** [review]

**Comment by gunnarmorling** [comment]
Applied; thx, @Naros and @keweishang for reviewing!

**Comment by Naros** [comment]
It looks like the CloudEvents test is failing for Vitess, I'll pull it down and see if I happened to have made a mistake somewhere.  It did pass locally so I'm not sure if perhaps there are some master changes that impact it or not.

**Comment by Naros** [comment]
Tests pass locally for Vitess, not sure why CI failed.

**Pull request merged**
