### PR TITLE
DBZ-6076: Add support for custom SourceInfoStructMaker for adding new fields to source field

### PR DESCRIPTION
**Pull request by adasari**

### CODE REVIEW

**Comment by jpechane** [comment]
@adasari This does not compile against https://github.com/debezium/debezium/pull/4258

**Comment by adasari** [comment]
I missed to commit updated test cases. just pushed now.

**Comment by jpechane** [comment]
@adasari Still the same problem

**Comment by adasari** [comment]
@jpechane it is failing as it is unable to recognize the debezium's main branch changes in debezium's DBZ-6076 branch. I have rebased debezium's DBZ-6707 branch and its build is failing because of other repo's build failures. is there a way to break this cyclic build dependencies to make builds succeed ?

**Comment by jpechane** [comment]
@adasari I rebased the PR and added a new commit

**Comment by adasari** [comment]
I have added new field to per connector config.

**Pull request merged**
