### PR TITLE
DBZ-2906 Sanitise DECIMAL string from VStream

### PR DESCRIPTION
**Pull request by keweishang**
https://issues.redhat.com/browse/DBZ-2906

### CODE REVIEW

**Review by rgibaiev — APPROVED** [review]

**Comment by rgibaiev** [comment]
Note for Gunnar - we will remove this logic when this bug is fixed inside Vitess VStream core

**Review by gunnarmorling — APPROVED** [review]
LGTM, feel free to merge once the build has passed. Can you also log a follow-up issue for tracking that upstream bug and reverting the work-around once it's resolved there? Thx!

**Comment by keweishang** [comment]
Good idea. A follow-up issue is created: https://issues.redhat.com/browse/DBZ-2908

**Comment by gunnarmorling** [comment]
Thx!

**Pull request merged**
