### PR TITLE
Upgrade to Vitess 17 in itests

### PR DESCRIPTION
**Pull request by twthorn**
Upgrade vitess version. Needed to test table copy resuming logic of "snapshots".

### CODE REVIEW

**Comment by twthorn** [comment]
Online DDL gets stuck in "running" state causing a test to fail, will look into this

**Comment by twthorn** [comment]
DDL failures still occurring, continuing to look into this...

**Comment by twthorn** [comment]
@jpechane This PR is ready for review. Thank you for your patience

**Comment by jpechane** [comment]
@twthorn Great job, applied!

**Pull request merged**
