### PR TITLE
DBZ-4464 Add missing snapshot repo

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-4464

### CODE REVIEW

**Review by gunnarmorling — COMMENTED** [review]
Interesting, why does it not suffice to get this from the parent POM?

**Comment by jpechane** [comment]
Because there is no relative path to parent pom and as it is repo separate to the one where parent pom is present you'd presicribe the naming and location of directories.

**Comment by gunnarmorling** [comment]
Ok, so the intention is to suppose a local build of the Vitess repo without having built _debezium/debezium_ before, right? I don't think this should ever happen on CI though, because there each job should build the main repo itself. If that's not the case somewhere, that should be fixed.

**Comment by gunnarmorling** [comment]
In particular, the build failure [here](https://github.com/debezium/debezium/runs/4559043190?check_suite_focus=true) should be handled by having that failing job build the _debezium-embedded module to as part of its build step for the main repo.

**Comment by gunnarmorling** [comment]
Pushed a change to the Vitess workflow in the main repo and this made the failure linked above go away. Hence happy to resolve this one now.

**Pull request merged**
