### PR TITLE
DBZ-3618: StringIndexOutOfBoundsException thrown while handling UTF-8 characters

### PR DESCRIPTION
**Pull request by piee9818**
Please refer to the issues #36 and [DBZ-3618](https://issues.redhat.com/browse/DBZ-3618)

### CODE REVIEW

**Review by keweishang — APPROVED** [review]
LGTM 👍 Thanks for the contribution!

**Comment by keweishang** [comment]
Hi @piee9818, can you submit a Debezium ticket first. An example ticket: https://issues.redhat.com/browse/DBZ-2851
The use `git commit --amend` to change your commit message to the format to start with the ticket number `DBZ-xxx`. Otherwise, the CI wouldn't pass. Thanks.

**Comment by piee9818** [comment]
Hi @keweishang, I submitted a Debezium ticket and changed the commit message. Thanks for the guide.

**Comment by gunnarmorling** [comment]
Thanks a lot, @piee9818! Could you only reauthor the commit using an e-mail address linked to your GH account as described [here](https://dev.to/duhbhavesh/why-my-commits-aren-t-showing-up-on-github-contributions-graph-3a2h)? Thx again!

**Comment by keweishang** [comment]
Hi @piee9818, would it be possible to add a test for this specific case. A good place to add this test is [here](https://github.com/debezium/debezium-connector-vitess/blob/b8b3e55c2e32976e8735ecb603b14061c3631d1b/src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java#L114)

**Comment by piee9818** [comment]
Hi, @keweishang
I added a test code for `ko` and `ja` but not `emoji`. Because the case of `emoji` needs to set the database to utf8mb4.
I will keep watching and supporting this repository, Thanks for your efforts a lot :)

**Comment by gunnarmorling** [comment]
Thanks a lot, @piee9818!

@keweishang, I think we can merge this one?

**Comment by gunnarmorling** [comment]
Rebased and applied. Added one commit to assert the column values, too. Thanks a lot, @piee9818!

**Pull request closed without merging**
